# Introduction

This repository is based on code from elmu's electronic doorlock project (see `archive` folder). This project was a real-use, working application to manage access to a house using encrypted DESFire cards from NXP.

What it does is changing the target to a more modular application, where the card verification and door control is separated. The central control mechanism that links those two components can be anything that communicates via MQTT.

A PC-plus-FT232H dongle based programmer application is provided, to manually write user IDs on cards.

## Project Structure

The top folders

common:: shared, generic C++ libraries and applications (CMake-based), and *global configuration*
common-esp32:: shared, esp32-specific libaries ("components")
esp32-cardreader:: esp32 application reading NFC cards and pubslishing extracted user IDs via MQTT

### Common

config:: the one central place to define your secret keys used to encrypt cards and MQTT communication
cardwriter:: desktop CLI application to verify and write cards via a FT232H USB/SPI dongle
external:: some CMake magic to find and integrate your locally installed FTDI dongle libraries
libdesfire:: re-factored NXP PN532 library from elmu (now with runtime hardware abstraction)
libdesfire_tests:: unit tests for rewritten PN532 message parsing abstraction
pn532-ft232h:: PN532 interface implementation via FT232H, working for SPI. Tried I2C but since the FT232H does not support the clock stretching applied by the PN532, it seems to be a dead end..
test-ft232h:: some basic system test to verify / diagnose basic FT232H + PN532 operations

## Card reader application (ESP32)

### Configuration (ESP-IDF menuconfig)

You can set up your specific MQTT subject, encryption etc. under the `MQTT` component settings. For the PN532 specific GPIO pins, they can be changed in the `PN532 GPIO Pins` section.

## Using PN532 from a PC via a FT232H USB Dongle

### Required libraries

* You need to get the ft2xx user space driver (dll or static) as provided by FTDI (https://ftdichip.com/drivers/d2xx-drivers/), including a lib and header file.
* You will also need the MPSSE library, which works on top of the ft2xx library (https://ftdichip.com/software-examples/mpsse-projects/libmpsse-spi-examples/). It includes the sources and you can build it yourself (I had to do that for my Win11 Arm64). I chose to use the static version of that library, see link:src/pn532-ft232h/CMakeLists.txt[CMakeLists.txt] of the `pn532-ft232h` library.

#### Making the FTDI libraries accessible in this project

Since you will have _your_ version of these libraries, depending on your system, and you may want to put them where _you_ find it practical, you will have to tell CMake how to find them, for example using your local user configuration. I think it is rather good practice to not have any user-specific settings with local paths included in this repository.

In Visual Studio Code, you may add something like this to your user settings JSON file:

[,json]
----
"cmake.configureSettings": {
		"CMAKE_TOOLCHAIN_FILE": "C:/Users/hagen/cmake/global_toolchain.cmake"
----

...where you define additional include and library paths in that toolchain file, for example

[,json]
----
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} /IC:/Users/hagen/Documents/ft232h")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT} /LIBPATH:C:/Users/hagen/Documents/ft232h")
----